{
 "title": "my diplom tms dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "blackbox_http_duration_seconds_processing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"calc.default.svc.cluster.local:5000\", job=\"blackbox_http\", phase=\"processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blackbox_dns_lookup_time_seconds_tcp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"calc.default.svc.cluster.local:5000\", job=\"blackbox_tcp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blackbox_http_duration_seconds_connect",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"calc.default.svc.cluster.local:5000\", job=\"blackbox_http\", phase=\"connect\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blackbox_dns_lookup_time_seconds_http",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"calc.default.svc.cluster.local:5000\", job=\"blackbox_http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blackbox_http_content_length",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_content_length{instance=\"calc.default.svc.cluster.local:5000\", job=\"blackbox_http\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}