version: '3.9'
services:
  jenkins-server:
    depends_on:
      - jenkins-docker
    image: ghcr.io/lodisav-devops/myjenkins:casc
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      JENKINS_URL: ${JENKINS_URL}
      DOCKER_HOST: tcp://jenkins-docker:2375
      DOCKER_CERT_PATH: ""
      DOCKER_TLS_VERIFY: ""
    secrets:
      - github_ssh
      - github_pat
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/ubuntu/jenkins/casc_configs:/var/jenkins_home/casc_configs/
    networks:
      - jenkins-network
  jenkins-docker:
    image: ghcr.io/lodisav-devops/docker:kubectl
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      KUBECONFIG: "/home/jenkins/.kube/config"
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/ubuntu/.kube:/home/jenkins/.kube/
    networks:
      - jenkins-network

volumes:
  jenkins-data:

networks:
  jenkins-network:

secrets:
  github_ssh:
    file: /home/ubuntu/.ssh/id_rsa
  github_pat:
    file: /home/ubuntu/.github/github_pat
