apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit
  annotations:
spec:
  rules:
  - host: "reddit"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: calc
            port:
              number: 5000
